# Generated by Django 4.0.6 on 2022-07-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
