# Generated by Django 4.0.6 on 2022-07-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
