# Generated by Django 4.0.6 on 2022-07-27 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('rating', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date_updated', models.DateTimeField(auto_now=True)),
                ('ordered_by', models.CharField(max_length=50)),
                ('ordered_address', models.CharField(max_length=100)),
                ('ordered_city', models.CharField(max_length=50)),
                ('ordered_state', models.CharField(max_length=50)),
                ('ordered_zip', models.CharField(max_length=10)),
                ('ordered_phone', models.CharField(max_length=10)),
                ('ordered_email', models.EmailField(max_length=254)),
                ('ordered_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordered_status', models.CharField(max_length=50)),
                ('items', models.ManyToManyField(to='main_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
