# Generated by Django 4.0.6 on 2022-07-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_title_product_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='ProductImage',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='test/'),
        ),
    ]
