# Generated by Django 4.0.6 on 2022-07-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_photo_productimage_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='banana/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.FileField(upload_to='media/'),
        ),
    ]
